{
  "comments": [
    {
      "key": {
        "uuid": "8ec42329_8a42a73d",
        "filename": "tests/test_zuul_layout.py",
        "patchSetId": 7
      },
      "lineNbr": 208,
      "author": {
        "id": 24
      },
      "writtenOn": "2015-07-18T20:27:54Z",
      "side": 1,
      "message": "Those are exceptions. Will we want to deal with them eventually one day :-)",
      "revId": "1cf20f925e09b2f82e852195f646a23a02e0fa7d",
      "serverId": "e9e9afe9-4712-486d-8885-f54b72dd1951",
      "unresolved": false
    }
  ]
}